# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
 stripe_api_key: sk_test_TqtmN8TopLe0QAOr3rGfMkrR
 stripe_publishable_key: pk_test_qF753us5wvdAbRbdYZr8Jmh3
#
# 
production:
 stripe_api_key: sk_live_1sgEsjT9gwF1svoHfTSmbzwa
 stripe_publishable_key: pk_live_4K1H1PnlxLWywCKnVhirDo9c
